[include]
files=/etc/supervisord-condor.conf

[program:jupyter]
user=submituser
directory=/home/submituser
environment=JUPYTER_RUNTIME_DIR=/home/submituser,HOME=/home/submituser
command = jupyter-lab --ip 0.0.0.0 --port 8888
stderr_logfile=/tmp/jupyter.err.log
stdout_logfile=/tmp/jupyter.out.log

[program:setup_ssh]
user=submituser
startsecs = 0
autorestart = false
command = sh -c '
    mkdir -p /home/submituser/.ssh
    cp /etc/ssh_config /home/submituser/.ssh/config
    '
